export const MENU_LISTS = [
  { id: 1, novelList: '한국 소설' },
  { id: 2, novelList: '영미 소설' },
  { id: 3, novelList: '일본 소설' },
  { id: 4, novelList: '중국 소설' },
  { id: 5, novelList: '북유럽 소설' },
  { id: 6, novelList: '독일 소설' },
  { id: 7, novelList: '프랑스 소설' },
  { id: 8, novelList: '기타 국가 소설' },
  { id: 9, novelList: 'IT 비즈니스' },
  { id: 10, novelList: '개발/프로그래밍' },
  { id: 11, novelList: '컴퓨터/앱 활용' },
  { id: 12, novelList: 'IT 자격증' },
  { id: 13, novelList: 'IT 해외원서' },
];
